/**
A string "aBIY" is said to be a well-ordered word as each of the letters are in sequential manner regardless of case. 
So, "AbLe" is not a well-ordered word. You are a anti-hacker. you have a number of character sequences. 
Your task is to generate all possible well-ordered word that can be generated by those numbers of given character
 sequences.
*/
import java.util.ArrayList;

public class SubstringIncreasingCharacters {
	public static void main(String[] args){
		String str = "DisAble";
		ArrayList<String> li = getSubstrings("", str.toLowerCase()); 
				//getIncreasingSubstrings(str.toLowerCase());
		for(String s: li)
		{
			System.out.println("string: "+s);
		}
	}
	public static ArrayList<String> getSubstrings(String prefix, String remaining)
	{
		ArrayList<String> l = new ArrayList<String>();
		if(remaining==null || remaining.isEmpty()){
			l.add(prefix);
			return l;
		}
		for(int i=0;i<remaining.length();i++)
		{
			if(prefix.isEmpty() || ((prefix.charAt(prefix.length()-1) < remaining.charAt(i)))){
				l.addAll(getSubstrings(prefix+remaining.substring(i,i+1), remaining.substring(i+1)));
			}
		}
		if(l.size()==0 && prefix!=null && !prefix.isEmpty())
			l.addAll(getSubstrings(prefix,""));
		return l;
	}
}
